global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'paladin'
    environment: 'production'

scrape_configs:
  # Backend API metrics
  - job_name: 'paladin-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    # Uncomment when postgres_exporter is added

  # Redis/KeyDB metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    # Uncomment when redis_exporter is added

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    # Uncomment when node_exporter is added

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      # Configure when alertmanager is added

rule_files:
  # - "alert_rules.yml"
  # Add alert rules here
